#!/usr/bin/python
import boto3, time, requests, socket, os, sys
import botocore.exceptions

from sg.waagent.logger import NGFwLogger
from azurelinuxagent.common import logger

LOGFILE = "/data/diagnostics/awsha-{}.log".format(os.getpid())
logger.DEFAULT_LOGGER = NGFwLogger(LOGFILE)

ROUTE_TABLE_FILE="/data/route-tables"
PROBE_PORT=22
TIMEOUT=2
EC2_METADATA_URL_BASE='http://169.254.169.254/latest'
EC2_METADATA_URL="{}/meta-data".format(EC2_METADATA_URL_BASE)

OPENSSL_CACERT_FILE = "/data/config/policy/latest/inspection/ca-bundle.pem"
if not os.path.exists(OPENSSL_CACERT_FILE):
    OPENSSL_CACERT_FILE = "/data/config/tls/ca-bundle.pem"
    assert os.path.exists(OPENSSL_CACERT_FILE)
logger.info("PEM bundle found: {}".format(OPENSSL_CACERT_FILE))

def getMetadata(url):
    r = requests.get(url)
    #Metadata service returns plaintext here
    return requests.get(url).text

def getMetadataValue(key):
    return getMetadata("{}/{}".format(EC2_METADATA_URL,key))

os.environ['REQUESTS_CA_BUNDLE'] = OPENSSL_CACERT_FILE
ec2 = boto3.resource('ec2', region_name='eu-west-3',api_version='2016-09-15')
ec2_client = boto3.client('ec2', region_name='eu-west-3')
#route tables to monitor
route_tables = []
with open(ROUTE_TABLE_FILE) as f:
    candidate = f.readline()
    while candidate:
        if candidate.startswith('rtb-'):
            route_table = ec2.RouteTable(candidate.rstrip())
            route_tables.append(route_table)
        candidate = f.readline()
instance = ec2.Instance(getMetadataValue('instance-id'))

#assuming eth0 is the destination
local_eni_id = None
local_eni_ip_address = None # Stash current private IP of this host.

primary_eni_ip_address = "10.119.0.4"
primari_eni = ec2_client.describe_network_interfaces(
    Filters=[
        {
            'Name': 'addresses.private-ip-address',
            'Values': [primary_eni_ip_address]
        }
    ]
)
primary_eni_id = primari_eni['NetworkInterfaceId']

secondary_eni_ip_address = "10.119.0.20"
secondary_eni = ec2_client.describe_network_interfaces(
    Filters=[
        {
            'Name': 'addresses.private-ip-address',
            'Values': [secondary_eni_ip_address]
        }
    ]
)
secondary_eni_id = secondary_eni['NetworkInterfaceId']

primary_dc_ip_address = "10.21.52.13"


# Assume the local_eni is DeviceIndex 0 if there is only 1 interface
# Or assume the local_eni is DeviceIndex 1 if there is more than 1
# TODO this is a temporary fix, this should really come from a conf file
# or something
for interface in instance.network_interfaces_attribute:
    #WAN interface index = 0
    if interface['Attachment']['DeviceIndex'] == 0:
        local_eni_id = interface['NetworkInterfaceId']
        local_eni_ip_address = interface['PrivateIpAddress']

logger.info("Local WAN (facing DC) eni is {} : IP {}".format(local_eni_id, local_eni_ip_address))
logger.info('Watching {}'.format(route_tables))

while True:
    time.sleep(1)
    sys.stdout.flush()
    sys.stderr.flush()
    for table in route_tables:
        table.reload()
        for route in table.routes_attribute:
            need_swap = False
            if 'NetworkInterfaceId' not in route.keys():
                continue #route not going to NGFW, skipping
            remote_eni = ec2.NetworkInterface(route['NetworkInterfaceId'])
            try:
                current_ip = remote_eni.private_ip_address
                if route['State'] == 'blackhole':
                    #do not even test route as it is detected as broken by platform
                    logger.info('AWS detected {} as blackhole'.format(remote_eni))
                    need_swap = True
                # elif current_ip == local_eni_ip_address:
                #     pass # Skipping probe, we are the current route eni gateway
                else:
                    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                    s.settimeout(TIMEOUT)
                    try:
                        s.connect((primary_eni_ip_address,PROBE_PORT))
                        #need_swap = True if current_ip == secondary_eni_ip_address else False
                    except socket.error as e:
                        logger.info("Error probing local ENI {} port {},{}".format(
                            primary_eni_ip_address,PROBE_PORT,e))
                        need_swap = True
                    if not need_swap:
                        #check the connectivity over the tunnel
                        #if the it's successful close the connection
                        try:
                            s.create_connection((primary_dc_ip_address,PROBE_PORT),TIMEOUT,(local_eni_ip_address, 0))
                            #need_swap = True if current_ip == secondary_eni_ip_address else False
                        except socket.error as e:
                            logger.info("Error probing on-premise FW {} port {} using source IP {},{}".format(
                                primary_dc_ip_address,PROBE_PORT,local_eni_ip_address,e))
                            need_swap = True
                        if not need_swap:
                            s.close
                if need_swap:
                    #modify target interface
                    route_obj = ec2.Route(table.id,route['DestinationCidrBlock'])
                    logger.info('Previous route: {}'.format(route))
                    if current_ip == primary_eni_ip_address:
                        logger.info('Modifying route to use secondary eni {}'.format(secondary_eni_id))
                        route_obj.replace(route['DestinationCidrBlock'],
                            NetworkInterfaceId=secondary_eni_id)
                        logger.info('Modifying route done')
                    #else: secondary is blackhole is down, so keep the route on seconday, nothing to do.
                    if current_ip == secondary_eni_ip_address:
                        logger.info('Modifying route back to use primary eni {}'.format(primary_eni_id))
                        route_obj.replace(route['DestinationCidrBlock'],
                            NetworkInterfaceId=primary_eni_id)
                        logger.info('Modifying route done')
            except botocore.exceptions.ClientError as e:
                logger.error(str(e))